// export const DEFAULT_ACTION = 'app/SignUpPage/DEFAULT_ACTION';
export default {
  SIGNUP_FORM_CHANGED: 'SIGNUP_FORM_CHANGED',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  REQUEST_SIGNUPPAGE_FROM_MAINPAGE: 'REQUEST_SIGNUPPAGE_FROM_MAINPAGE',
};
