export const DEFAULT_ACTION = 'app/AdminPage/DEFAULT_ACTION';
export default {
  ADMIN_PAGE_LOADING: 'ADMIN_PAGE_LOADING',
  ADMIN_PAGE_LOADING_FAILURE: 'ADMIN_PAGE_LOADING_FAILURE',
  ADMIN_PAGE_LOADING_SUCCESS: 'ADMIN_PAGE_LOADING_SUCCESS',

  INPUT_CHANGED: 'INPUT_CHANGED',

  DIALOG_ADMIN_FORM_CHANGED: 'DIALOG_ADMIN_FORM_CHANGED',

  REQUEST_CREATE_NEW_ADMIN: 'REQUEST_CREATE_NEW_ADMIN',
  ADMIN_CREATED_SUCCESSFULLY: 'ADMIN_CREATED_SUCCESSFULLY',
  ADMIN_CREATED_FAILURE: 'ADMIN_CREATED_FAILURE',
  NEW_ADMIN_DIALOG_ERRORS: 'NEW_ADMIN_DIALOG_ERRORS',

  LOG_OUT: 'LOG_OUT',
};
