export const DEFAULT_ACTION = 'app/MainPage/DEFAULT_ACTION';
export default {
  MAIN_PAGE_LOADING: 'MAIN_PAGE_LOADING',
  MAIN_PAGE_LOADING_SUCCUSS: 'MAIN_PAGE_LOADING_SUCCUSS',
  MAIN_PAGE_LOADING_FAILURE: 'MAIN_PAGE_LOADING_FAILURE',

  PREPARE_SLIDER: 'PREPARE_SLIDER',
  PREPARE_SLIDER_SUCCESS: 'PREPARE_SLIDER_SUCCESS',
  PREPARE_SLIDER_FAILURE: 'PREPARE_SLIDER_FAILURE',

  SIGN_OUT: 'SIGN_OUT',

  HEAD_TO_CREARTE_PORTFOLIO: 'HEAD_TO_CREARTE_PORTFOLIO',
};
