export const DEFAULT_ACTION = 'app/MainPage/DEFAULT_ACTION';
export default {
  MAIN_PAGE_LOADING: 'MAIN_PAGE_LOADING',
  MAIN_PAGE_LOADING_SUCCUSS: 'MAIN_PAGE_LOADING_SUCCUSS',
  MAIN_PAGE_LOADING_FAILURE: 'MAIN_PAGE_LOADING_FAILURE',

  PREPARE_SLIDER: 'PREPARE_SLIDER',
  PREPARE_SLIDER_SUCCESS: 'PREPARE_SLIDER_SUCCESS',
  PREPARE_SLIDER_FAILURE: 'PREPARE_SLIDER_FAILURE',

  SIGN_OUT: 'SIGN_OUT',

  HEAD_TO_USER_PROFILE: 'HEAD_TO_USER_PROFILE',

  PERSONAL_INFO_FORM_CHANGED: 'PERSONAL_INFO_FORM_CHANGED',
  REQUEST_ADD_PERSONAL_INFO: 'REQUEST_ADD_PERSONAL_INFO',
  ADDING_INFO_SUCCESS: 'ADDING_INFO_SUCCESS',
  ADDING_INFO_FAILURE: 'ADDING_INFO_FAILURE',
  FORM_ADD_INFO_ERRORS: 'FORM_ADD_INFO_ERRORS',

  SKILLS_FORM_CHANGED: 'SKILLS_FORM_CHANGED',
  REQUEST_ADD_SKILLS: 'REQUEST_ADD_SKILLS',
  ADDING_SKILLS_SUCCESS: 'ADDING_SKILLS_SUCCESS',
  ADDING_SKILLS_FAILURE: 'ADDING_SKILLS_FAILURE',
  FORM_ADD_SKILLS_ERRORS: 'FORM_ADD_SKILLS_ERRORS',

  USER_EXPERIENCE_FORM_CHANGED: 'USER_EXPERIENCE_FORM_CHANGED',
  DATE_PICKER_CHANGED: 'DATE_PICKER_CHANGED',
  REQUEST_ADD_EXPERIENCE: 'REQUEST_ADD_EXPERIENCE',
  ADD_EXPERIENCE_SUCCESS: 'ADD_EXPERIENCE_SUCCESS',
  ADD_EXPERIENCE_FAILURE: 'ADD_EXPERIENCE_FAILURE',

  USER_EDUCATION_FORM_CHANGED: 'USER_EDUCATION_FORM_CHANGED',
  DROPDOWN_CHANGED: 'DROPDOWN_CHANGED',
  REQUEST_ADD_EDUCATION: 'REQUEST_ADD_EDUCATION',
  ADD_EDUCATION_SUCCESS: 'ADD_EDUCATION_SUCCESS',
  ADD_EDUCATION_FAILURE: 'ADD_EDUCATION_FAILURE',
};
