export const DEFAULT_ACTION = 'app/AdminSignIn/DEFAULT_ACTION';
export default {
  LOGIN_FORM_ADMIN_CHANGED: 'LOGIN_FORM_ADMIN_CHANGED',
  LOGIN_REQUEST_ADMINPAGE: 'LOGIN_REQUEST_ADMINPAGE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_ERRORS: 'LOGIN_ERRORS',
  REQUEST_LOGINPAGE_FROM_ADMINPAGE: 'REQUEST_LOGINPAGE_FROM_ADMINPAGE',
};
