export const CHANGE_USERNAME = 'boilerplate/LoginPage/CHANGE_USERNAME';

export default {
  LOGIN_FORM_CHANGED: 'LOGIN_FORM_CHANGED',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REQUEST_LOGINPAGE_FROM_MAINPAGE: 'REQUEST_LOGINPAGE_FROM_MAINPAGE',
  REQUEST_LOGINPAGE_FROM_ADMINPAGE: 'REQUEST_LOGINPAGE_FROM_ADMINPAGE',
};
